Add automatic doc generation back
terminusdb/terminusdb-docs pull request #50
Opened 2021-11-09 10:12 UTC by rrooij

2021-11-09 11:07 UTC, spl requested changes
I believe this fixes https://github.com/terminusdb/terminusdb-docs/issues/33 but not https://github.com/terminusdb/terminusdb-docs/issues/17. Is that correct?

2021-11-09 11:07 UTC, spl commented on .ci/generate_docs.sh
> +sudo apt install ronn
Is this for https://github.com/terminusdb/terminusdb-docs/issues/17? Do you need to call `make docs` or something else?

2021-11-12 13:52 UTC, rrooij commented
Fixed it. :smile:

2021-11-12 15:13 UTC, spl approved these changes

2021-11-12 15:13 UTC, merged